controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    tinker_controller:
      type: diff_drive_controller/DiffDriveController

tinker_controller:
  ros__parameters:
    left_wheel_names: ["fl_wheel_joint", 'rl_wheel_joint']
    right_wheel_names: ["fr_wheel_joint", 'rr_wheel_joint']

    wheel_separation: 0.41
    wheels_per_side: 2 # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.05

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal:  [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
    twist_covariance_diagonal: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]

    position_feedback: false
    open_loop: false
    enable_odom_tf: false

    cmd_vel_timeout: 0.5 # seconds
    publish_limited_velocity: true
    velocity_rolling_window_size: 10
    use_stamped_vel: False

    linear.x.has_velocity_limits: false
    linear.x.has_acceleration_limits: false
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 0.0
    linear.x.min_velocity: 0.0
    linear.x.max_acceleration: 0.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: false
    angular.z.has_acceleration_limits: false
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 0.0
    angular.z.min_velocity: 0.0
    angular.z.max_acceleration: 0.0
    angular.z.min_acceleration: 0.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0






















