/**:
    ros__parameters:
      registration_method: "NDT_OMP"
      score_threshold: 2.5
      ndt_resolution: 1.0
      ndt_step_size: 0.1
      ndt_num_threads: 0
      transform_epsilon: 0.01
      voxel_leaf_size: 0.2
      scan_max_range: 100.0
      scan_min_range: 1.0
      scan_period: 0.1
      use_pcd_map: true
      map_path: "/home/dssl/Projects/3d_localization/src/lidar_localization_ros2/map/map.pcd"
      set_initial_pose: false
      initial_pose_x: 0.7865956425666809
      initial_pose_y: -0.3229368031024933
      initial_pose_z: 0.0
      initial_pose_qx: 0.0
      initial_pose_qy: 0.0
      initial_pose_qz: 0.9999406575538987
      initial_pose_qw:  0.010894097974434204
      use_odom: false
      use_imu: false
      enable_debug: false
      global_frame_id: odom
      odom_frame_id: odom
      base_frame_id: base_link
